username = input("Как вас зовут?")
title = input("Ваша заметка")
content = input("Список дел")
status = input("Не выполнено")
created_date = input("Дата начала")
issue_date = input("Дата окончания")

print("Имя пользователя", username)
print("Заголовок", title)
print("Содержание", content)
print("Статус", status)
print("Дата создания", created_date)
print("Дата выполнения", issue_date)